version = "1.3.0"
builder = "spa"

[template_settings]
accent-color = "#2D4566"
background-color = "#121414"
highlight-color = "#73bed3"
autoreload = "1"
text-color = "#c7cfcc"
custom-color = "#f3a833"
